[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "microsoft.sharepoint.pages"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = []
# icon = "icon.png" # TODO: update icon.png
repository = "https://github.com/ballerina-platform/module-ballerinax-microsoft.sharepoint.pages"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
