// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

# SharePoint subset of the Microsoft Graph v1.0 OpenAPI specification (generated from graphexplorer.yaml).
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://graph.microsoft.com/v1.0/sites") returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # List baseSitePages
    #
    # + siteId - The unique identifier of site
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function listPages(string siteId, map<string|string[]> headers = {}, *ListPagesQueries queries) returns BaseSitePageCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create a page in the site pages list of a site
    #
    # + siteId - The unique identifier of site
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property 
    # + return - Created navigation property 
    remote isolated function createPages(string siteId, BaseSitePage payload, map<string|string[]> headers = {}) returns BaseSitePage|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get baseSitePage
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function getPages(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *GetPagesQueries queries) returns BaseSitePage|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete baseSitePage
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function deletePages(string siteId, string baseSitePageId, DeletePagesHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property pages in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    remote isolated function updatePages(string siteId, string baseSitePageId, BaseSitePage payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get createdByUser from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function getPageCreator(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *GetPageCreatorQueries queries) returns User|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/createdByUser`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get mailboxSettings property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Entity result 
    remote isolated function getPageCreatorMailbox(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *GetPageCreatorMailboxQueries queries) returns MailboxSettings|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/createdByUser/mailboxSettings`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update property mailboxSettings value.
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New property values 
    # + return - Success 
    remote isolated function updatePageCreatorMailbox(string siteId, string baseSitePageId, MailboxSettings payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/createdByUser/mailboxSettings`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get serviceProvisioningErrors property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function listPageCreatorServiceErrors(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *ListPageCreatorServiceErrorsQueries queries) returns ServiceProvisioningErrorCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/createdByUser/serviceProvisioningErrors`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function getPageCreatorServiceErrorsCount(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *GetPageCreatorServiceErrorsCountQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/createdByUser/serviceProvisioningErrors/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get lastModifiedByUser from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function getPageModifier(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *GetPageModifierQueries queries) returns User|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/lastModifiedByUser`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get mailboxSettings property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Entity result 
    remote isolated function getPageModifierMailbox(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *GetPageModifierMailboxQueries queries) returns MailboxSettings|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/lastModifiedByUser/mailboxSettings`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update property mailboxSettings value.
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New property values 
    # + return - Success 
    remote isolated function updatePageModifierMailbox(string siteId, string baseSitePageId, MailboxSettings payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/lastModifiedByUser/mailboxSettings`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get serviceProvisioningErrors property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function listPageModifierServiceErrors(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *ListPageModifierServiceErrorsQueries queries) returns ServiceProvisioningErrorCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/lastModifiedByUser/serviceProvisioningErrors`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function getPageModifierServiceErrorsCount(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *GetPageModifierServiceErrorsCountQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/lastModifiedByUser/serviceProvisioningErrors/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get SitePage
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Entity result 
    remote isolated function getSitePage(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *GetSitePageQueries queries) returns SitePage|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get canvasLayout from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function getSitePageCanvasLayout(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *GetSitePageCanvasLayoutQueries queries) returns CanvasLayout|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete navigation property canvasLayout for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function deleteSitePageCanvasLayout(string siteId, string baseSitePageId, DeleteSitePageCanvasLayoutHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property canvasLayout in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    remote isolated function updateSitePageCanvasLayout(string siteId, string baseSitePageId, CanvasLayout payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get horizontalSections from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function listHorizontalSections(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *ListHorizontalSectionsQueries queries) returns HorizontalSectionCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create new navigation property to horizontalSections for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property 
    # + return - Created navigation property 
    remote isolated function createHorizontalSection(string siteId, string baseSitePageId, HorizontalSection payload, map<string|string[]> headers = {}) returns HorizontalSection|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get horizontalSections from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function getHorizontalSection(string siteId, string baseSitePageId, string horizontalSectionId, map<string|string[]> headers = {}, *GetHorizontalSectionQueries queries) returns HorizontalSection|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete navigation property horizontalSections for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function deleteHorizontalSection(string siteId, string baseSitePageId, string horizontalSectionId, DeleteHorizontalSectionHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property horizontalSections in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    remote isolated function updateHorizontalSection(string siteId, string baseSitePageId, string horizontalSectionId, HorizontalSection payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get columns from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function listHSectionColumns(string siteId, string baseSitePageId, string horizontalSectionId, map<string|string[]> headers = {}, *ListHSectionColumnsQueries queries) returns HorizontalSectionColumnCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create new navigation property to columns for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property 
    # + return - Created navigation property 
    remote isolated function createHSectionColumn(string siteId, string baseSitePageId, string horizontalSectionId, HorizontalSectionColumn payload, map<string|string[]> headers = {}) returns HorizontalSectionColumn|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get columns from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function getHSectionColumn(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, map<string|string[]> headers = {}, *GetHSectionColumnQueries queries) returns HorizontalSectionColumn|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete navigation property columns for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function deleteHSectionColumn(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, DeleteHSectionColumnHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property columns in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    remote isolated function updateHSectionColumn(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, HorizontalSectionColumn payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get webparts from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function listHSectionColumnWebparts(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, map<string|string[]> headers = {}, *ListHSectionColumnWebpartsQueries queries) returns WebPartCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create new navigation property to webparts for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property 
    # + return - Created navigation property 
    remote isolated function createHSectionColumnWebpart(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, WebPart payload, map<string|string[]> headers = {}) returns WebPart|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get webparts from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function getHSectionColumnWebpart(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, string webPartId, map<string|string[]> headers = {}, *GetHSectionColumnWebpartQueries queries) returns WebPart|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts/${getEncodedUri(webPartId)}`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete navigation property webparts for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function deleteHSectionColumnWebpart(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, string webPartId, DeleteHSectionColumnWebpartHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts/${getEncodedUri(webPartId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property webparts in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    remote isolated function updateHSectionColumnWebpart(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, string webPartId, WebPart payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts/${getEncodedUri(webPartId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Invoke action getPositionOfWebPart
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function getHSectionColumnWebpartPosition(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, string webPartId, map<string|string[]> headers = {}) returns WebPartPositionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts/${getEncodedUri(webPartId)}/microsoft.graph.getPositionOfWebPart`;
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function getHSectionColumnWebpartsCount(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, map<string|string[]> headers = {}, *GetHSectionColumnWebpartsCountQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function getHSectionColumnsCount(string siteId, string baseSitePageId, string horizontalSectionId, map<string|string[]> headers = {}, *GetHSectionColumnsCountQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function getHSectionsCount(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *GetHSectionsCountQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get verticalSection from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function getVerticalSection(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *GetVerticalSectionQueries queries) returns VerticalSection|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete navigation property verticalSection for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function deleteVerticalSection(string siteId, string baseSitePageId, DeleteVerticalSectionHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property verticalSection in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    remote isolated function updateVerticalSection(string siteId, string baseSitePageId, VerticalSection payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get webparts from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function listVSectionWebparts(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *ListVSectionWebpartsQueries queries) returns WebPartCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create new navigation property to webparts for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property 
    # + return - Created navigation property 
    remote isolated function createVSectionWebpart(string siteId, string baseSitePageId, WebPart payload, map<string|string[]> headers = {}) returns WebPart|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get webparts from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function getVSectionWebpart(string siteId, string baseSitePageId, string webPartId, map<string|string[]> headers = {}, *GetVSectionWebpartQueries queries) returns WebPart|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts/${getEncodedUri(webPartId)}`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete navigation property webparts for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function deleteVSectionWebpart(string siteId, string baseSitePageId, string webPartId, DeleteVSectionWebpartHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts/${getEncodedUri(webPartId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property webparts in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    remote isolated function updateVSectionWebpart(string siteId, string baseSitePageId, string webPartId, WebPart payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts/${getEncodedUri(webPartId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Invoke action getPositionOfWebPart
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function getVSectionWebpartPosition(string siteId, string baseSitePageId, string webPartId, map<string|string[]> headers = {}) returns WebPartPositionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts/${getEncodedUri(webPartId)}/microsoft.graph.getPositionOfWebPart`;
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function getVSectionWebpartsCount(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *GetVSectionWebpartsCountQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get createdByUser from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function getSitePageCreator(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *GetSitePageCreatorQueries queries) returns User|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/createdByUser`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get mailboxSettings property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Entity result 
    remote isolated function getSitePageCreatorMailbox(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *GetSitePageCreatorMailboxQueries queries) returns MailboxSettings|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/createdByUser/mailboxSettings`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update property mailboxSettings value.
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New property values 
    # + return - Success 
    remote isolated function updateSitePageCreatorMailbox(string siteId, string baseSitePageId, MailboxSettings payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/createdByUser/mailboxSettings`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get serviceProvisioningErrors property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function listSitePageCreatorServiceErrors(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *ListSitePageCreatorServiceErrorsQueries queries) returns ServiceProvisioningErrorCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/createdByUser/serviceProvisioningErrors`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function getSitePageCreatorServiceErrorsCount(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *GetSitePageCreatorServiceErrorsCountQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/createdByUser/serviceProvisioningErrors/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get lastModifiedByUser from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function getSitePageModifier(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *GetSitePageModifierQueries queries) returns User|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/lastModifiedByUser`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get mailboxSettings property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Entity result 
    remote isolated function getSitePageModifierMailbox(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *GetSitePageModifierMailboxQueries queries) returns MailboxSettings|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/lastModifiedByUser/mailboxSettings`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update property mailboxSettings value.
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New property values 
    # + return - Success 
    remote isolated function updateSitePageModifierMailbox(string siteId, string baseSitePageId, MailboxSettings payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/lastModifiedByUser/mailboxSettings`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get serviceProvisioningErrors property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function listSitePageModifierServiceErrors(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *ListSitePageModifierServiceErrorsQueries queries) returns ServiceProvisioningErrorCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/lastModifiedByUser/serviceProvisioningErrors`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function getSitePageModifierServiceErrorsCount(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *GetSitePageModifierServiceErrorsCountQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/lastModifiedByUser/serviceProvisioningErrors/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get webParts from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function listSitePageWebParts(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *ListSitePageWebPartsQueries queries) returns WebPartCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create new navigation property to webParts for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property 
    # + return - Created navigation property 
    remote isolated function createSitePageWebPart(string siteId, string baseSitePageId, WebPart payload, map<string|string[]> headers = {}) returns WebPart|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get webParts from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function getSitePageWebPart(string siteId, string baseSitePageId, string webPartId, map<string|string[]> headers = {}, *GetSitePageWebPartQueries queries) returns WebPart|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts/${getEncodedUri(webPartId)}`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete webPart
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function deleteSitePageWebPart(string siteId, string baseSitePageId, string webPartId, DeleteSitePageWebPartHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts/${getEncodedUri(webPartId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property webParts in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    remote isolated function updateSitePageWebPart(string siteId, string baseSitePageId, string webPartId, WebPart payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts/${getEncodedUri(webPartId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Invoke action getPositionOfWebPart
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function getSitePageWebPartPosition(string siteId, string baseSitePageId, string webPartId, map<string|string[]> headers = {}) returns WebPartPositionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts/${getEncodedUri(webPartId)}/microsoft.graph.getPositionOfWebPart`;
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function getSitePageWebPartsCount(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *GetSitePageWebPartsCountQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Publish a site page
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + return - No content. The page was successfully published. 
    remote isolated function publishSitePage(string siteId, string baseSitePageId, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/publish`;
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get web parts by position
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function getSitePageWebPartsByPosition(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *GetSitePageWebPartsByPositionQueries queries) returns WebPartCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/getWebPartsByPosition`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function getPagesCount(string siteId, map<string|string[]> headers = {}, *GetPagesCountQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get SitePage
    #
    # + siteId - The unique identifier of site
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function listSitePages(string siteId, map<string|string[]> headers = {}, *ListSitePagesQueries queries) returns SitePageCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/microsoft.graph.sitePage`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function getSitePagesCount(string siteId, map<string|string[]> headers = {}, *GetSitePagesCountQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/microsoft.graph.sitePage/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }
}
