// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

# SharePoint subset of the Microsoft Graph v1.0 OpenAPI specification (generated from graphexplorer.yaml).
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://graph.microsoft.com/v1.0/sites") returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # List baseSitePages
    #
    # + siteId - The unique identifier of site
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function sitesListPages(string siteId, map<string|string[]> headers = {}, *SitesListPagesQueries queries) returns MicrosoftGraphBaseSitePageCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create a page in the site pages list of a site
    #
    # + siteId - The unique identifier of site
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property 
    # + return - Created navigation property 
    remote isolated function sitesCreatePages(string siteId, MicrosoftGraphBaseSitePage payload, map<string|string[]> headers = {}) returns MicrosoftGraphBaseSitePage|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get baseSitePage
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function sitesGetPages(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *SitesGetPagesQueries queries) returns MicrosoftGraphBaseSitePage|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete baseSitePage
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function sitesDeletePages(string siteId, string baseSitePageId, SitesDeletePagesHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property pages in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    remote isolated function sitesUpdatePages(string siteId, string baseSitePageId, MicrosoftGraphBaseSitePage payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get createdByUser from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function sitesPagesGetCreatedByUser(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *SitesPagesGetCreatedByUserQueries queries) returns MicrosoftGraphUser|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/createdByUser`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get mailboxSettings property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Entity result 
    remote isolated function sitesPagesCreatedByUserGetMailboxSettings(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *SitesPagesCreatedByUserGetMailboxSettingsQueries queries) returns MicrosoftGraphMailboxSettings|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/createdByUser/mailboxSettings`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update property mailboxSettings value.
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New property values 
    # + return - Success 
    remote isolated function sitesPagesCreatedByUserUpdateMailboxSettings(string siteId, string baseSitePageId, MicrosoftGraphMailboxSettings payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/createdByUser/mailboxSettings`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get serviceProvisioningErrors property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function sitesPagesCreatedByUserListServiceProvisioningErrors(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *SitesPagesCreatedByUserListServiceProvisioningErrorsQueries queries) returns MicrosoftGraphServiceProvisioningErrorCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/createdByUser/serviceProvisioningErrors`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function sitesPagesCreatedByUserServiceProvisioningErrorsGetCount7e89(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *SitesPagesCreatedByUserServiceProvisioningErrorsGetCount7e89Queries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/createdByUser/serviceProvisioningErrors/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get lastModifiedByUser from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function sitesPagesGetLastModifiedByUser(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *SitesPagesGetLastModifiedByUserQueries queries) returns MicrosoftGraphUser|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/lastModifiedByUser`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get mailboxSettings property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Entity result 
    remote isolated function sitesPagesLastModifiedByUserGetMailboxSettings(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *SitesPagesLastModifiedByUserGetMailboxSettingsQueries queries) returns MicrosoftGraphMailboxSettings|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/lastModifiedByUser/mailboxSettings`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update property mailboxSettings value.
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New property values 
    # + return - Success 
    remote isolated function sitesPagesLastModifiedByUserUpdateMailboxSettings(string siteId, string baseSitePageId, MicrosoftGraphMailboxSettings payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/lastModifiedByUser/mailboxSettings`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get serviceProvisioningErrors property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function sitesPagesLastModifiedByUserListServiceProvisioningErrors(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *SitesPagesLastModifiedByUserListServiceProvisioningErrorsQueries queries) returns MicrosoftGraphServiceProvisioningErrorCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/lastModifiedByUser/serviceProvisioningErrors`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function sitesPagesLastModifiedByUserServiceProvisioningErrorsGetCount6cf6(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *SitesPagesLastModifiedByUserServiceProvisioningErrorsGetCount6cf6Queries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/lastModifiedByUser/serviceProvisioningErrors/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get SitePage
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Entity result 
    remote isolated function sitesGetPagesAsSitePage(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *SitesGetPagesAsSitePageQueries queries) returns MicrosoftGraphSitePage|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get canvasLayout from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function sitesPagesAsSitePageGetCanvasLayout(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *SitesPagesAsSitePageGetCanvasLayoutQueries queries) returns MicrosoftGraphCanvasLayout|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete navigation property canvasLayout for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function sitesPagesAsSitePageDeleteCanvasLayout(string siteId, string baseSitePageId, SitesPagesAsSitePageDeleteCanvasLayoutHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property canvasLayout in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    remote isolated function sitesPagesAsSitePageUpdateCanvasLayout(string siteId, string baseSitePageId, MicrosoftGraphCanvasLayout payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get horizontalSections from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function sitesPagesAsSitePageCanvasLayoutListHorizontalSections(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *SitesPagesAsSitePageCanvasLayoutListHorizontalSectionsQueries queries) returns MicrosoftGraphHorizontalSectionCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create new navigation property to horizontalSections for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property 
    # + return - Created navigation property 
    remote isolated function sitesPagesAsSitePageCanvasLayoutCreateHorizontalSections(string siteId, string baseSitePageId, MicrosoftGraphHorizontalSection payload, map<string|string[]> headers = {}) returns MicrosoftGraphHorizontalSection|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get horizontalSections from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function sitesPagesAsSitePageCanvasLayoutGetHorizontalSections(string siteId, string baseSitePageId, string horizontalSectionId, map<string|string[]> headers = {}, *SitesPagesAsSitePageCanvasLayoutGetHorizontalSectionsQueries queries) returns MicrosoftGraphHorizontalSection|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete navigation property horizontalSections for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function sitesPagesAsSitePageCanvasLayoutDeleteHorizontalSections(string siteId, string baseSitePageId, string horizontalSectionId, SitesPagesAsSitePageCanvasLayoutDeleteHorizontalSectionsHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property horizontalSections in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    remote isolated function sitesPagesAsSitePageCanvasLayoutUpdateHorizontalSections(string siteId, string baseSitePageId, string horizontalSectionId, MicrosoftGraphHorizontalSection payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get columns from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function sitesPagesAsSitePageCanvasLayoutHorizontalSectionsListColumns(string siteId, string baseSitePageId, string horizontalSectionId, map<string|string[]> headers = {}, *SitesPagesAsSitePageCanvasLayoutHorizontalSectionsListColumnsQueries queries) returns MicrosoftGraphHorizontalSectionColumnCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create new navigation property to columns for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property 
    # + return - Created navigation property 
    remote isolated function sitesPagesAsSitePageCanvasLayoutHorizontalSectionsCreateColumns(string siteId, string baseSitePageId, string horizontalSectionId, MicrosoftGraphHorizontalSectionColumn payload, map<string|string[]> headers = {}) returns MicrosoftGraphHorizontalSectionColumn|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get columns from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function sitesPagesAsSitePageCanvasLayoutHorizontalSectionsGetColumns(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, map<string|string[]> headers = {}, *SitesPagesAsSitePageCanvasLayoutHorizontalSectionsGetColumnsQueries queries) returns MicrosoftGraphHorizontalSectionColumn|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete navigation property columns for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function sitesPagesAsSitePageCanvasLayoutHorizontalSectionsDeleteColumns(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, SitesPagesAsSitePageCanvasLayoutHorizontalSectionsDeleteColumnsHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property columns in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    remote isolated function sitesPagesAsSitePageCanvasLayoutHorizontalSectionsUpdateColumns(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, MicrosoftGraphHorizontalSectionColumn payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get webparts from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function sitesPagesAsSitePageCanvasLayoutHorizontalSectionsColumnsListWebparts(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, map<string|string[]> headers = {}, *SitesPagesAsSitePageCanvasLayoutHorizontalSectionsColumnsListWebpartsQueries queries) returns MicrosoftGraphWebPartCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create new navigation property to webparts for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property 
    # + return - Created navigation property 
    remote isolated function sitesPagesAsSitePageCanvasLayoutHorizontalSectionsColumnsCreateWebparts(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, MicrosoftGraphWebPart payload, map<string|string[]> headers = {}) returns MicrosoftGraphWebPart|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get webparts from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function sitesPagesAsSitePageCanvasLayoutHorizontalSectionsColumnsGetWebparts(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, string webPartId, map<string|string[]> headers = {}, *SitesPagesAsSitePageCanvasLayoutHorizontalSectionsColumnsGetWebpartsQueries queries) returns MicrosoftGraphWebPart|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts/${getEncodedUri(webPartId)}`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete navigation property webparts for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function sitesPagesAsSitePageCanvasLayoutHorizontalSectionsColumnsDeleteWebparts(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, string webPartId, SitesPagesAsSitePageCanvasLayoutHorizontalSectionsColumnsDeleteWebpartsHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts/${getEncodedUri(webPartId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property webparts in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    remote isolated function sitesPagesAsSitePageCanvasLayoutHorizontalSectionsColumnsUpdateWebparts(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, string webPartId, MicrosoftGraphWebPart payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts/${getEncodedUri(webPartId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Invoke action getPositionOfWebPart
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function sitesSitePagesBaseSitePageMicrosoftGraphSitePageCanvasLayoutHorizontalSectionsHorizontalSectionColumnsHorizontalSectionColumnWebpartsWebPartGetPositionOfWebPart(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, string webPartId, map<string|string[]> headers = {}) returns WebPartPositionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts/${getEncodedUri(webPartId)}/microsoft.graph.getPositionOfWebPart`;
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function sitesPagesAsSitePageCanvasLayoutHorizontalSectionsColumnsWebpartsGetCountBbb9(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, map<string|string[]> headers = {}, *SitesPagesAsSitePageCanvasLayoutHorizontalSectionsColumnsWebpartsGetCountBbb9Queries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function sitesPagesAsSitePageCanvasLayoutHorizontalSectionsColumnsGetCount9382(string siteId, string baseSitePageId, string horizontalSectionId, map<string|string[]> headers = {}, *SitesPagesAsSitePageCanvasLayoutHorizontalSectionsColumnsGetCount9382Queries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function sitesPagesAsSitePageCanvasLayoutHorizontalSectionsGetCount38fc(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *SitesPagesAsSitePageCanvasLayoutHorizontalSectionsGetCount38fcQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get verticalSection from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function sitesPagesAsSitePageCanvasLayoutGetVerticalSection(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *SitesPagesAsSitePageCanvasLayoutGetVerticalSectionQueries queries) returns MicrosoftGraphVerticalSection|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete navigation property verticalSection for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function sitesPagesAsSitePageCanvasLayoutDeleteVerticalSection(string siteId, string baseSitePageId, SitesPagesAsSitePageCanvasLayoutDeleteVerticalSectionHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property verticalSection in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    remote isolated function sitesPagesAsSitePageCanvasLayoutUpdateVerticalSection(string siteId, string baseSitePageId, MicrosoftGraphVerticalSection payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get webparts from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function sitesPagesAsSitePageCanvasLayoutVerticalSectionListWebparts(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *SitesPagesAsSitePageCanvasLayoutVerticalSectionListWebpartsQueries queries) returns MicrosoftGraphWebPartCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create new navigation property to webparts for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property 
    # + return - Created navigation property 
    remote isolated function sitesPagesAsSitePageCanvasLayoutVerticalSectionCreateWebparts(string siteId, string baseSitePageId, MicrosoftGraphWebPart payload, map<string|string[]> headers = {}) returns MicrosoftGraphWebPart|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get webparts from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function sitesPagesAsSitePageCanvasLayoutVerticalSectionGetWebparts(string siteId, string baseSitePageId, string webPartId, map<string|string[]> headers = {}, *SitesPagesAsSitePageCanvasLayoutVerticalSectionGetWebpartsQueries queries) returns MicrosoftGraphWebPart|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts/${getEncodedUri(webPartId)}`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete navigation property webparts for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function sitesPagesAsSitePageCanvasLayoutVerticalSectionDeleteWebparts(string siteId, string baseSitePageId, string webPartId, SitesPagesAsSitePageCanvasLayoutVerticalSectionDeleteWebpartsHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts/${getEncodedUri(webPartId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property webparts in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    remote isolated function sitesPagesAsSitePageCanvasLayoutVerticalSectionUpdateWebparts(string siteId, string baseSitePageId, string webPartId, MicrosoftGraphWebPart payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts/${getEncodedUri(webPartId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Invoke action getPositionOfWebPart
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function sitesSitePagesBaseSitePageMicrosoftGraphSitePageCanvasLayoutVerticalSectionWebpartsWebPartGetPositionOfWebPart(string siteId, string baseSitePageId, string webPartId, map<string|string[]> headers = {}) returns WebPartPositionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts/${getEncodedUri(webPartId)}/microsoft.graph.getPositionOfWebPart`;
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function sitesPagesAsSitePageCanvasLayoutVerticalSectionWebpartsGetCount185f(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *SitesPagesAsSitePageCanvasLayoutVerticalSectionWebpartsGetCount185fQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get createdByUser from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function sitesPagesAsSitePageGetCreatedByUser(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *SitesPagesAsSitePageGetCreatedByUserQueries queries) returns MicrosoftGraphUser|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/createdByUser`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get mailboxSettings property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Entity result 
    remote isolated function sitesPagesAsSitePageCreatedByUserGetMailboxSettings(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *SitesPagesAsSitePageCreatedByUserGetMailboxSettingsQueries queries) returns MicrosoftGraphMailboxSettings|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/createdByUser/mailboxSettings`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update property mailboxSettings value.
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New property values 
    # + return - Success 
    remote isolated function sitesPagesAsSitePageCreatedByUserUpdateMailboxSettings(string siteId, string baseSitePageId, MicrosoftGraphMailboxSettings payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/createdByUser/mailboxSettings`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get serviceProvisioningErrors property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function sitesPagesAsSitePageCreatedByUserListServiceProvisioningErrors(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *SitesPagesAsSitePageCreatedByUserListServiceProvisioningErrorsQueries queries) returns MicrosoftGraphServiceProvisioningErrorCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/createdByUser/serviceProvisioningErrors`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function sitesPagesAsSitePageCreatedByUserServiceProvisioningErrorsGetCountA4bd(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *SitesPagesAsSitePageCreatedByUserServiceProvisioningErrorsGetCountA4bdQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/createdByUser/serviceProvisioningErrors/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get lastModifiedByUser from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function sitesPagesAsSitePageGetLastModifiedByUser(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *SitesPagesAsSitePageGetLastModifiedByUserQueries queries) returns MicrosoftGraphUser|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/lastModifiedByUser`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get mailboxSettings property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Entity result 
    remote isolated function sitesPagesAsSitePageLastModifiedByUserGetMailboxSettings(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *SitesPagesAsSitePageLastModifiedByUserGetMailboxSettingsQueries queries) returns MicrosoftGraphMailboxSettings|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/lastModifiedByUser/mailboxSettings`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update property mailboxSettings value.
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New property values 
    # + return - Success 
    remote isolated function sitesPagesAsSitePageLastModifiedByUserUpdateMailboxSettings(string siteId, string baseSitePageId, MicrosoftGraphMailboxSettings payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/lastModifiedByUser/mailboxSettings`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get serviceProvisioningErrors property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function sitesPagesAsSitePageLastModifiedByUserListServiceProvisioningErrors(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *SitesPagesAsSitePageLastModifiedByUserListServiceProvisioningErrorsQueries queries) returns MicrosoftGraphServiceProvisioningErrorCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/lastModifiedByUser/serviceProvisioningErrors`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function sitesPagesAsSitePageLastModifiedByUserServiceProvisioningErrorsGetCount9ea6(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *SitesPagesAsSitePageLastModifiedByUserServiceProvisioningErrorsGetCount9ea6Queries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/lastModifiedByUser/serviceProvisioningErrors/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get webParts from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function sitesPagesAsSitePageListWebParts(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *SitesPagesAsSitePageListWebPartsQueries queries) returns MicrosoftGraphWebPartCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create new navigation property to webParts for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property 
    # + return - Created navigation property 
    remote isolated function sitesPagesAsSitePageCreateWebParts(string siteId, string baseSitePageId, MicrosoftGraphWebPart payload, map<string|string[]> headers = {}) returns MicrosoftGraphWebPart|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get webParts from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function sitesPagesAsSitePageGetWebParts(string siteId, string baseSitePageId, string webPartId, map<string|string[]> headers = {}, *SitesPagesAsSitePageGetWebPartsQueries queries) returns MicrosoftGraphWebPart|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts/${getEncodedUri(webPartId)}`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete webPart
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function sitesPagesAsSitePageDeleteWebParts(string siteId, string baseSitePageId, string webPartId, SitesPagesAsSitePageDeleteWebPartsHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts/${getEncodedUri(webPartId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property webParts in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    remote isolated function sitesPagesAsSitePageUpdateWebParts(string siteId, string baseSitePageId, string webPartId, MicrosoftGraphWebPart payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts/${getEncodedUri(webPartId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Invoke action getPositionOfWebPart
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function sitesSitePagesBaseSitePageMicrosoftGraphSitePageWebPartsWebPartGetPositionOfWebPart(string siteId, string baseSitePageId, string webPartId, map<string|string[]> headers = {}) returns WebPartPositionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts/${getEncodedUri(webPartId)}/microsoft.graph.getPositionOfWebPart`;
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function sitesPagesAsSitePageWebPartsGetCountEb99(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *SitesPagesAsSitePageWebPartsGetCountEb99Queries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function sitesPagesGetCount3155(string siteId, map<string|string[]> headers = {}, *SitesPagesGetCount3155Queries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get SitePage
    #
    # + siteId - The unique identifier of site
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function sitesListPagesAsSitePage(string siteId, map<string|string[]> headers = {}, *SitesListPagesAsSitePageQueries queries) returns MicrosoftGraphSitePageCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/microsoft.graph.sitePage`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function sitesPagesGetCountAsSitePageC4ed(string siteId, map<string|string[]> headers = {}, *SitesPagesGetCountAsSitePageC4edQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/microsoft.graph.sitePage/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }
}
