// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

# SharePoint subset of the Microsoft Graph v1.0 OpenAPI specification (generated from graphexplorer.yaml).
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://graph.microsoft.com/v1.0/sites") returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # List baseSitePages
    #
    # + siteId - The unique identifier of site
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function listPages(string siteId, map<string|string[]> headers = {}, *ListPagesQueries queries) returns BaseSitePageCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create a page in the site pages list of a site
    #
    # + siteId - The unique identifier of site
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property 
    # + return - Created navigation property 
    remote isolated function createPages(string siteId, BaseSitePage payload, map<string|string[]> headers = {}) returns BaseSitePage|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get baseSitePage
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function getPages(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *GetPagesQueries queries) returns BaseSitePage|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete baseSitePage
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function deletePages(string siteId, string baseSitePageId, DeletePagesHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property pages in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    remote isolated function updatePages(string siteId, string baseSitePageId, BaseSitePage payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get createdByUser from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function pagesGetCreatedByUser(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *PagesGetCreatedByUserQueries queries) returns User|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/createdByUser`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get mailboxSettings property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Entity result 
    remote isolated function pagesCreatedByUserGetMailboxSettings(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *PagesCreatedByUserGetMailboxSettingsQueries queries) returns MailboxSettings|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/createdByUser/mailboxSettings`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update property mailboxSettings value.
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New property values 
    # + return - Success 
    remote isolated function pagesCreatedByUserUpdateMailboxSettings(string siteId, string baseSitePageId, MailboxSettings payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/createdByUser/mailboxSettings`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get serviceProvisioningErrors property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function pagesCreatedByUserListServiceProvisioningErrors(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *PagesCreatedByUserListServiceProvisioningErrorsQueries queries) returns ServiceProvisioningErrorCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/createdByUser/serviceProvisioningErrors`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function pagesCreatedByUserServiceProvisioningErrorsGetCount(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *PagesCreatedByUserServiceProvisioningErrorsGetCountQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/createdByUser/serviceProvisioningErrors/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get lastModifiedByUser from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function pagesGetLastModifiedByUser(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *PagesGetLastModifiedByUserQueries queries) returns User|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/lastModifiedByUser`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get mailboxSettings property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Entity result 
    remote isolated function pagesLastModifiedByUserGetMailboxSettings(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *PagesLastModifiedByUserGetMailboxSettingsQueries queries) returns MailboxSettings|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/lastModifiedByUser/mailboxSettings`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update property mailboxSettings value.
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New property values 
    # + return - Success 
    remote isolated function pagesLastModifiedByUserUpdateMailboxSettings(string siteId, string baseSitePageId, MailboxSettings payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/lastModifiedByUser/mailboxSettings`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get serviceProvisioningErrors property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function pagesLastModifiedByUserListServiceProvisioningErrors(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *PagesLastModifiedByUserListServiceProvisioningErrorsQueries queries) returns ServiceProvisioningErrorCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/lastModifiedByUser/serviceProvisioningErrors`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function pagesLastModifiedByUserServiceProvisioningErrorsGetCount(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *PagesLastModifiedByUserServiceProvisioningErrorsGetCountQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/lastModifiedByUser/serviceProvisioningErrors/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get SitePage
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Entity result 
    remote isolated function getPagesAsSitePage(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *GetPagesAsSitePageQueries queries) returns SitePage|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get canvasLayout from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function pagesAsSitePageGetCanvasLayout(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *PagesAsSitePageGetCanvasLayoutQueries queries) returns CanvasLayout|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete navigation property canvasLayout for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function pagesAsSitePageDeleteCanvasLayout(string siteId, string baseSitePageId, PagesAsSitePageDeleteCanvasLayoutHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property canvasLayout in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    remote isolated function pagesAsSitePageUpdateCanvasLayout(string siteId, string baseSitePageId, CanvasLayout payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get horizontalSections from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function pagesAsSitePageCanvasLayoutListHorizontalSections(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *PagesAsSitePageCanvasLayoutListHorizontalSectionsQueries queries) returns HorizontalSectionCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create new navigation property to horizontalSections for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property 
    # + return - Created navigation property 
    remote isolated function pagesAsSitePageCanvasLayoutCreateHorizontalSections(string siteId, string baseSitePageId, HorizontalSection payload, map<string|string[]> headers = {}) returns HorizontalSection|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get horizontalSections from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function pagesAsSitePageCanvasLayoutGetHorizontalSections(string siteId, string baseSitePageId, string horizontalSectionId, map<string|string[]> headers = {}, *PagesAsSitePageCanvasLayoutGetHorizontalSectionsQueries queries) returns HorizontalSection|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete navigation property horizontalSections for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function pagesAsSitePageCanvasLayoutDeleteHorizontalSections(string siteId, string baseSitePageId, string horizontalSectionId, PagesAsSitePageCanvasLayoutDeleteHorizontalSectionsHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property horizontalSections in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    remote isolated function pagesAsSitePageCanvasLayoutUpdateHorizontalSections(string siteId, string baseSitePageId, string horizontalSectionId, HorizontalSection payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get columns from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function pagesAsSitePageCanvasLayoutHorizontalSectionsListColumns(string siteId, string baseSitePageId, string horizontalSectionId, map<string|string[]> headers = {}, *PagesAsSitePageCanvasLayoutHorizontalSectionsListColumnsQueries queries) returns HorizontalSectionColumnCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create new navigation property to columns for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property 
    # + return - Created navigation property 
    remote isolated function pagesAsSitePageCanvasLayoutHorizontalSectionsCreateColumns(string siteId, string baseSitePageId, string horizontalSectionId, HorizontalSectionColumn payload, map<string|string[]> headers = {}) returns HorizontalSectionColumn|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get columns from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function pagesAsSitePageCanvasLayoutHorizontalSectionsGetColumns(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, map<string|string[]> headers = {}, *PagesAsSitePageCanvasLayoutHorizontalSectionsGetColumnsQueries queries) returns HorizontalSectionColumn|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete navigation property columns for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function pagesAsSitePageCanvasLayoutHorizontalSectionsDeleteColumns(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, PagesAsSitePageCanvasLayoutHorizontalSectionsDeleteColumnsHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property columns in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    remote isolated function pagesAsSitePageCanvasLayoutHorizontalSectionsUpdateColumns(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, HorizontalSectionColumn payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get webparts from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function pagesAsSitePageCanvasLayoutHorizontalSectionsColumnsListWebparts(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, map<string|string[]> headers = {}, *PagesAsSitePageCanvasLayoutHorizontalSectionsColumnsListWebpartsQueries queries) returns WebPartCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create new navigation property to webparts for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property 
    # + return - Created navigation property 
    remote isolated function pagesAsSitePageCanvasLayoutHorizontalSectionsColumnsCreateWebparts(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, WebPart payload, map<string|string[]> headers = {}) returns WebPart|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get webparts from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function pagesAsSitePageCanvasLayoutHorizontalSectionsColumnsGetWebparts(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, string webPartId, map<string|string[]> headers = {}, *PagesAsSitePageCanvasLayoutHorizontalSectionsColumnsGetWebpartsQueries queries) returns WebPart|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts/${getEncodedUri(webPartId)}`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete navigation property webparts for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function pagesAsSitePageCanvasLayoutHorizontalSectionsColumnsDeleteWebparts(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, string webPartId, PagesAsSitePageCanvasLayoutHorizontalSectionsColumnsDeleteWebpartsHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts/${getEncodedUri(webPartId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property webparts in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    remote isolated function pagesAsSitePageCanvasLayoutHorizontalSectionsColumnsUpdateWebparts(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, string webPartId, WebPart payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts/${getEncodedUri(webPartId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Invoke action getPositionOfWebPart
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function pagesAsSitePageCanvasLayoutHorizontalSectionsColumnsWebpartsGetPositionOfWebPart(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, string webPartId, map<string|string[]> headers = {}) returns WebPartPositionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts/${getEncodedUri(webPartId)}/microsoft.graph.getPositionOfWebPart`;
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function pagesAsSitePageCanvasLayoutHorizontalSectionsColumnsWebpartsGetCount(string siteId, string baseSitePageId, string horizontalSectionId, string horizontalSectionColumnId, map<string|string[]> headers = {}, *PagesAsSitePageCanvasLayoutHorizontalSectionsColumnsWebpartsGetCountQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function pagesAsSitePageCanvasLayoutHorizontalSectionsColumnsGetCount(string siteId, string baseSitePageId, string horizontalSectionId, map<string|string[]> headers = {}, *PagesAsSitePageCanvasLayoutHorizontalSectionsColumnsGetCountQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function pagesAsSitePageCanvasLayoutHorizontalSectionsGetCount(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *PagesAsSitePageCanvasLayoutHorizontalSectionsGetCountQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get verticalSection from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function pagesAsSitePageCanvasLayoutGetVerticalSection(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *PagesAsSitePageCanvasLayoutGetVerticalSectionQueries queries) returns VerticalSection|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete navigation property verticalSection for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function pagesAsSitePageCanvasLayoutDeleteVerticalSection(string siteId, string baseSitePageId, PagesAsSitePageCanvasLayoutDeleteVerticalSectionHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property verticalSection in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    remote isolated function pagesAsSitePageCanvasLayoutUpdateVerticalSection(string siteId, string baseSitePageId, VerticalSection payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get webparts from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function pagesAsSitePageCanvasLayoutVerticalSectionListWebparts(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *PagesAsSitePageCanvasLayoutVerticalSectionListWebpartsQueries queries) returns WebPartCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create new navigation property to webparts for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property 
    # + return - Created navigation property 
    remote isolated function pagesAsSitePageCanvasLayoutVerticalSectionCreateWebparts(string siteId, string baseSitePageId, WebPart payload, map<string|string[]> headers = {}) returns WebPart|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get webparts from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function pagesAsSitePageCanvasLayoutVerticalSectionGetWebparts(string siteId, string baseSitePageId, string webPartId, map<string|string[]> headers = {}, *PagesAsSitePageCanvasLayoutVerticalSectionGetWebpartsQueries queries) returns WebPart|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts/${getEncodedUri(webPartId)}`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete navigation property webparts for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function pagesAsSitePageCanvasLayoutVerticalSectionDeleteWebparts(string siteId, string baseSitePageId, string webPartId, PagesAsSitePageCanvasLayoutVerticalSectionDeleteWebpartsHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts/${getEncodedUri(webPartId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property webparts in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    remote isolated function pagesAsSitePageCanvasLayoutVerticalSectionUpdateWebparts(string siteId, string baseSitePageId, string webPartId, WebPart payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts/${getEncodedUri(webPartId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Invoke action getPositionOfWebPart
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function pagesAsSitePageCanvasLayoutVerticalSectionWebpartsGetPositionOfWebPart(string siteId, string baseSitePageId, string webPartId, map<string|string[]> headers = {}) returns WebPartPositionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts/${getEncodedUri(webPartId)}/microsoft.graph.getPositionOfWebPart`;
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function pagesAsSitePageCanvasLayoutVerticalSectionWebpartsGetCount(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *PagesAsSitePageCanvasLayoutVerticalSectionWebpartsGetCountQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get createdByUser from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function pagesAsSitePageGetCreatedByUser(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *PagesAsSitePageGetCreatedByUserQueries queries) returns User|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/createdByUser`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get mailboxSettings property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Entity result 
    remote isolated function pagesAsSitePageCreatedByUserGetMailboxSettings(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *PagesAsSitePageCreatedByUserGetMailboxSettingsQueries queries) returns MailboxSettings|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/createdByUser/mailboxSettings`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update property mailboxSettings value.
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New property values 
    # + return - Success 
    remote isolated function pagesAsSitePageCreatedByUserUpdateMailboxSettings(string siteId, string baseSitePageId, MailboxSettings payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/createdByUser/mailboxSettings`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get serviceProvisioningErrors property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function pagesAsSitePageCreatedByUserListServiceProvisioningErrors(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *PagesAsSitePageCreatedByUserListServiceProvisioningErrorsQueries queries) returns ServiceProvisioningErrorCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/createdByUser/serviceProvisioningErrors`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function pagesAsSitePageCreatedByUserServiceProvisioningErrorsGetCount(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *PagesAsSitePageCreatedByUserServiceProvisioningErrorsGetCountQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/createdByUser/serviceProvisioningErrors/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get lastModifiedByUser from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function pagesAsSitePageGetLastModifiedByUser(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *PagesAsSitePageGetLastModifiedByUserQueries queries) returns User|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/lastModifiedByUser`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get mailboxSettings property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Entity result 
    remote isolated function pagesAsSitePageLastModifiedByUserGetMailboxSettings(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *PagesAsSitePageLastModifiedByUserGetMailboxSettingsQueries queries) returns MailboxSettings|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/lastModifiedByUser/mailboxSettings`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update property mailboxSettings value.
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New property values 
    # + return - Success 
    remote isolated function pagesAsSitePageLastModifiedByUserUpdateMailboxSettings(string siteId, string baseSitePageId, MailboxSettings payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/lastModifiedByUser/mailboxSettings`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get serviceProvisioningErrors property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function pagesAsSitePageLastModifiedByUserListServiceProvisioningErrors(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *PagesAsSitePageLastModifiedByUserListServiceProvisioningErrorsQueries queries) returns ServiceProvisioningErrorCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/lastModifiedByUser/serviceProvisioningErrors`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function pagesAsSitePageLastModifiedByUserServiceProvisioningErrorsGetCount(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *PagesAsSitePageLastModifiedByUserServiceProvisioningErrorsGetCountQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/lastModifiedByUser/serviceProvisioningErrors/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get webParts from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function pagesAsSitePageListWebParts(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *PagesAsSitePageListWebPartsQueries queries) returns WebPartCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create new navigation property to webParts for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property 
    # + return - Created navigation property 
    remote isolated function pagesAsSitePageCreateWebParts(string siteId, string baseSitePageId, WebPart payload, map<string|string[]> headers = {}) returns WebPart|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get webParts from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    remote isolated function pagesAsSitePageGetWebParts(string siteId, string baseSitePageId, string webPartId, map<string|string[]> headers = {}, *PagesAsSitePageGetWebPartsQueries queries) returns WebPart|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts/${getEncodedUri(webPartId)}`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete webPart
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function pagesAsSitePageDeleteWebParts(string siteId, string baseSitePageId, string webPartId, PagesAsSitePageDeleteWebPartsHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts/${getEncodedUri(webPartId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property webParts in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    remote isolated function pagesAsSitePageUpdateWebParts(string siteId, string baseSitePageId, string webPartId, WebPart payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts/${getEncodedUri(webPartId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Invoke action getPositionOfWebPart
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function pagesAsSitePageWebPartsGetPositionOfWebPart(string siteId, string baseSitePageId, string webPartId, map<string|string[]> headers = {}) returns WebPartPositionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts/${getEncodedUri(webPartId)}/microsoft.graph.getPositionOfWebPart`;
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function pagesAsSitePageWebPartsGetCount(string siteId, string baseSitePageId, map<string|string[]> headers = {}, *PagesAsSitePageWebPartsGetCountQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function pagesGetCount(string siteId, map<string|string[]> headers = {}, *PagesGetCountQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get SitePage
    #
    # + siteId - The unique identifier of site
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    remote isolated function listPagesAsSitePage(string siteId, map<string|string[]> headers = {}, *ListPagesAsSitePageQueries queries) returns SitePageCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/microsoft.graph.sitePage`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    remote isolated function pagesGetCountAsSitePage(string siteId, map<string|string[]> headers = {}, *PagesGetCountAsSitePageQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/microsoft.graph.sitePage/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }
}
